export const MEDIA_CONFIG = {
  manga: {
    label: 'マンガ',
    labelEn: 'Manga',
    icon: '📖',
    color: '#7060ff',
    dataUrl: '/manga_map_light.json',
    tagIdfUrl: '/api/tags/idf',
    tagListUrl: '/api/tags',
    detailUrl: '/api/manga',
    storageKey: 'manga',
    available: true,
    description: '漫画作品の類似空間マップ',
  },
  anime: {
    label: 'アニメ',
    labelEn: 'Anime',
    icon: '🎬',
    color: '#06b6d4',
    dataUrl: '/anime_map.json',
    tagIdfUrl: '/anime_tag_idf.json',
    tagListUrl: '/anime_tag_list.json',
    storageKey: 'anime',
    available: false,
    description: 'アニメ作品の類似空間マップ',
  },
  movie: {
    label: '映画',
    labelEn: 'Movie',
    icon: '🎥',
    color: '#f97316',
    dataUrl: '/movie_map.json',
    tagIdfUrl: '/movie_tag_idf.json',
    tagListUrl: '/movie_tag_list.json',
    storageKey: 'movie',
    available: false,
    description: '映画作品の類似空間マップ',
  },
  novel: {
    label: '小説',
    labelEn: 'Novel',
    icon: '📚',
    color: '#22c55e',
    dataUrl: '/novel_map.json',
    tagIdfUrl: '/novel_tag_idf.json',
    tagListUrl: '/novel_tag_list.json',
    storageKey: 'novel',
    available: false,
    description: '小説作品の類似空間マップ',
  },
}
